// "use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers, { mantineDefaultColorScheme, mantineTheme } from './providers';
import { ColorSchemeScript, MantineProvider } from "@mantine/core"
import { cookies } from "next/headers"


export const metadata: Metadata = {
  title: 'imitate - copy - duplicate',
  description: 'Generated by create next app',
  icons: '/bear-svgrepo-com.svg',
  openGraph: {
    siteName: 'cj copy site',
    description: "cj copy",
  }
}


export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode,
  modal: React.ReactNode
}) {


  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/bear-svgrepo-com.svg" />
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Providers>
            {children} 
          </Providers> 
        </MantineProvider>
                          
      </body>
    </html>
  )
}
